In [5]:
def divide(x,y):
    try:
        result=x//y
        print("Yeah! your answer is: ", result)
    except:
        print("Sorry you are diving by zero")
divide(5,0)
        

Sorry you are diving by zero


In [2]:
country=["Americans", "Indians"]
action=["Play", "watch"]
game=["Baseball","cricket"]

phrase_list = [(a+" "+ b + " " + c) for a in country for b in action for c in game]
for line in phrase_list:
 print (line)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [11]:
np.column_stack([x**(N-i-1) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [14]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [15]:
np.vander(x, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [16]:
np.linalg.det(np.vander(x))

48.00000000000007

In [17]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48